export const GET_ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST';
export const GET_ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS';
export const GET_ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
